# Generated by Django 2.1.3 on 2019-01-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, upload_to='songs'),
        ),
    ]
