# Generated by Django 2.1.3 on 2019-01-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_remove_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='player.Song'),
        ),
    ]
