# Generated by Django 2.1.3 on 2019-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0008_auto_20190109_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
