# Generated by Django 2.1.3 on 2019-01-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0009_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='playlist',
        ),
    ]
